### ISSUE TITLE
Unable to build Hibernate SessionFactory

### ISSUE THREAD

**Issue by rashideeql** [FX-HAO/keycloak-phone-authenticator#10]
Hi,

Need help with the error below during Keycloak server startup

`javax.persistence.PersistenceException: [PersistenceUnit: keycloak-default] Unable to build Hibernate SessionFactory`

I have executed these steps:

1. Download Keycloak Server 13.0.1
2. Pull from git this repo and excute mvn clean & mvn package
3. Create /providers in the keycloak folder and copy the jar

I can see the table "verification_code" is created in my postgres database but during startup getting the error mentioned

* I have attached the full error log for your reference

Thanks

[hibernate-session-error-log.txt](https://github.com/FX-HAO/keycloak-phone-authenticator/files/6982310/hibernate-session-error-log.txt)

**Comment by FX-HAO** [comment]
seems like this error was caused by `org.hibernate.proxy.HibernateProxy is not found`. what jars did you register? could you try it following [the example Dockerfile](https://github.com/FX-HAO/keycloak-phone-authenticator/blob/master/examples/Dockerfile)?

**Comment by rashideeql** [comment]
Thanks for pointing the error about `org.hibernate.proxy.HibernateProxy is not found`. 

Somehow deploying by just putting the jar in /providers folder does not work. 

I followed your advice to use the CLI to add the modules. It deployed successfully. 

Thanks @FX-HAO
