### ISSUE TITLE
How do I set up Direct grant flow?

### ISSUE THREAD

**Issue by gisly** [FX-HAO/keycloak-phone-authenticator#12]
I don't understand this part of the instruction:

```
Configuration
Configure your REALM to use the phone number and verification code Authentication. First create a new REALM (or select a previously created REALM).

Under Authentication > Flows:

Copy the 'Direct Grant' flow to 'Direct grant with phone' flow
Click on 'Actions > Add execution' on the 'Provide Phone Number' line
Click on 'Actions > Add execution' on the 'Provide Verification Code' line
Set both of 'Provide Phone Number' and 'Provide Verification Code' to 'REQUIRED'

```
There are no Provide Phone Number' line or  'Provide Verification Code' line, so how should I set up the direct grant flow?

**Comment by fuxinhao-crypto** [comment]
Please make sure you set up this library correctly. you can confirm it on 'Server Info' -> 'Provider'. 
![image](https://user-images.githubusercontent.com/81133379/150717174-0dc2ed49-472b-4246-946c-dda84114dd20.png)
If you don't know how to integrate this library into Keycloak, please refer to https://github.com/FX-HAO/keycloak-phone-authenticator/tree/master/examples

**Comment by FX-HAO** [comment]
Please make sure you set up this library correctly. you can confirm it on 'Server Info' -> 'Provider'.
![image](https://user-images.githubusercontent.com/6838487/150717387-3a86839c-b6b6-4c85-b6b4-373492fea014.png)

If you don't know how to integrate this library into Keycloak, please refer to https://github.com/FX-HAO/keycloak-phone-authenticator/tree/master/examples

**Comment by gisly** [comment]
Thank you! I changed the display name of the providers and could not find them.

**Comment by gisly** [comment]
Could you please help again with this issue?
I can now send the SMS code and get the list of codes. However, I cannot get the token using a request to /auth/realms/{realm}/protocol/openid-connect/token, getting the "Invalid user credentials" error. I've added logging, and it seems that VerificationCodeAuthenticator.authenticate is not called at all, although I've set the new "Direct grant with SMS" flow for the client id I am using. Should I do something else to make keycloak call the VerificationCodeAuthenticator?

**Comment by gisly** [comment]
Sorry, I managed to do it. I actually changed searchForUserByUserAttribute to the more recent searchForUserByUserAttributeStream and it started working suddenly
