### ISSUE TITLE
How To Access VerificationCode table if I already have an external db setup? 

### ISSUE THREAD

**Issue by dev-aakash1998** [FX-HAO/keycloak-phone-authenticator#8]
Hi, thanks for this package, I am using it currently to enable OTP flow, I was wondering where this `Verification Code` table might be.  I am using an external PGSQL DB for all keycloak data storage, do I need to do some changes in the code so that this table is also created in the same DB?  Or would this table be just added to the existing Keycloak DB? Thanks in advance.

**Comment by FX-HAO** [comment]
Once you register this module, a table named `verification_code` will be automatically created in the existing keycloak database. So there's nothing you need to do.

**Comment by dev-aakash1998** [comment]
Yeap got it! Thanks!
